#Each new term in the Fibonacci sequence is generated by adding the previousious two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

current = 0
previous1 = 1
previous2 = 1
sum = 0
while True:
    current = previous1 + previous2
    if current >= 4000000:
        break
    if current % 2 == 0:
        sum += current
    previous2 = previous1
    previous1 = current
    continue

print(sum)